repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Test
        entry: go test -v ./...
        language: system
        stages: [commit]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
